export const defaultUser: IUser = {
    last_seen_at: null,
    cover_image_thumbnail_url: null,
    brand: null,
    id: null,
    email_confirmed: true,
    phone_confirmed: true,
    timezone: "",
    active_brand: null,
    agents: null,
    personal_room: null,
    user_type: 'Agent',
    first_name: null,
    last_name: null,
    display_name: '',
    email: '',
    phone_number: null,
    is_shadow: false,
    profile_image_url: null,
    cover_image_url: null,
    email_signature: null,
    access_token: '',
    refresh_token: '',
    facebook: undefined,
    twitter: undefined,
    linkedin: undefined,
    youtube: undefined,
    instagram: undefined,
    type: 'user',
    created_at: 0,
    updated_at: 0
}

export const defaultRole: IDealRole = {
    agent: null,
    agent_brokerwolf_id: null,
    brokerwolf_contact_type: null,
    brokerwolf_id: null,
    brokerwolf_row_version: null,
    checklist: [],
    commission_dollar: null,
    commission_percentage: null,
    company_title: "",
    created_at: Number((new Date()).getTime()),
    created_by: null,
    deal: "",
    deleted_at: null,
    current_address: null,
    email: "",
    id: null,
    legal_first_name: "",
    legal_full_name: "",
    legal_last_name: "",
    legal_middle_name: null,
    legal_prefix: "",
    mlsid: null,
    phone_number: "",
    role: "Seller",
    role_type: 'Person',
    type: "",
    updated_at: Number((new Date()).getTime()),
    user: defaultUser,
    brand: null,
}

export const roleStep: { [key: string]: 2 | 3| 4 | 5 } = {
    Seller: 2, 
    Buyer: 3,
    BuyerPowerOfAttorney: 4,
    SellerPowerOfAttorney: 5,
}

export const roleText: { [key: string]: string } = {
    Seller: "seller", 
    Buyer: "buyer",
    BuyerPowerOfAttorney: "buyer's attorney",
    SellerPowerOfAttorney: "seller's attorney",
}